//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorrectMe.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorrectMe.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Recommended).
        /// </summary>
        public static string DefaultModel {
            get {
                return ResourceManager.GetString("DefaultModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while correcting the text. Error = {0}.
        /// </summary>
        public static string Error_CorrectingTheTextError {
            get {
                return ResourceManager.GetString("Error_CorrectingTheTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the language.
        /// </summary>
        public static string Error_CouldNotDetermineTheLanguage {
            get {
                return ResourceManager.GetString("Error_CouldNotDetermineTheLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while detecting input language. Error = {0}.
        /// </summary>
        public static string Error_DetectingInputLanguageError {
            get {
                return ResourceManager.GetString("Error_DetectingInputLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key cannot be empty..
        /// </summary>
        public static string Error_TheKeyCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_TheKeyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve models. Verify the API Key. Error= {0}.
        /// </summary>
        public static string ErrorRetrievingModels {
            get {
                return ResourceManager.GetString("ErrorRetrievingModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI Compatible.
        /// </summary>
        public static string GPTSelection_Custom {
            get {
                return ResourceManager.GetString("GPTSelection_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepSeek.
        /// </summary>
        public static string GPTSelection_DeepSeek {
            get {
                return ResourceManager.GetString("GPTSelection_DeepSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI.
        /// </summary>
        public static string GPTSelection_OpenAI {
            get {
                return ResourceManager.GetString("GPTSelection_OpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenRouter.
        /// </summary>
        public static string GPTSelection_OpenRouter {
            get {
                return ResourceManager.GetString("GPTSelection_OpenRouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:Arabic;1:Dutch;2:*English;3:French;4:German;5:Hindi;6:Italian;7:Japanese;8:Korean;9:Portuguese (Brazilian);10:Portuguese (European);11:Russian;12:Spanish;13:Swedish;14:Turkish;15:Chinese
        ///.
        /// </summary>
        public static string LanguagesToTranslate {
            get {
                return ResourceManager.GetString("LanguagesToTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct me! ({0}).
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language detected is: {0}
        ///--------------------------------------------------------------------------
        ///
        ///.
        /// </summary>
        public static string Msg_DetectedLanguage {
            get {
                return ResourceManager.GetString("Msg_DetectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting input language....
        /// </summary>
        public static string msg_DetectingInputLanguage {
            get {
                return ResourceManager.GetString("msg_DetectingInputLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set the GPT model and API key in the settings menu..
        /// </summary>
        public static string Msg_SetOpenAIAPIKeyInTheSettingsMenu {
            get {
                return ResourceManager.GetString("Msg_SetOpenAIAPIKeyInTheSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgBoxTitle_Error {
            get {
                return ResourceManager.GetString("MsgBoxTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You need to configure the GPT to use the corrector.
        /// </summary>
        public static string msgConfigureKey {
            get {
                return ResourceManager.GetString("msgConfigureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string msgLoading {
            get {
                return ResourceManager.GetString("msgLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open to load....
        /// </summary>
        public static string msgOpenToLoad {
            get {
                return ResourceManager.GetString("msgOpenToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting input language....
        /// </summary>
        public static string Wait_DetectingLanguage {
            get {
                return ResourceManager.GetString("Wait_DetectingLanguage", resourceCulture);
            }
        }
    }
}
